### ISSUE TITLE
Possibly a bad test in transfer_spec.rb

### ISSUE THREAD

**Issue by justinddaniel** [learn-co-curriculum/oo-banking#1]
describe '#execute_transaction' do
    it "can execute a successful transaction between two accounts" do
      transfer.execute_transaction  #### [line 50 in solution branch; throws an error because transfer object is no longer defined.]
      expect(amanda.balance).to eq(950)
      expect(avi.balance).to eq(1050)
      expect(transfer.status).to eq("complete")
    end

*****Fix:    *****

describe '#execute_transaction' do
     let(:avi) { BankAccount.new("Avi") }   # add these from lines 3-7 back in so the variables are once again defined in this test scope
     let(:amanda) { BankAccount.new("Amanda") }
     let(:transfer) { Transfer.new(amanda, avi, 50) }
     let(:bad_transfer) { Transfer.new(amanda, avi, 4000) }
    it "can execute a successful transaction between two accounts" do
      transfer.execute_transaction
      expect(amanda.balance).to eq(950)
      expect(avi.balance).to eq(1050)
      expect(transfer.status).to eq("complete")
    end

**Comment by drakeltheryuujin** [comment]
Hi @justinddaniel,

Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
