### ISSUE TITLE
#both_valid? tests do not refer to instance variables

### ISSUE THREAD

**Issue by AdamKing0126** [learn-co-curriculum/oo-banking#11]
expect(transfer_class.scan(/sender.valid\? \&\& receiver.valid\?/).length).to eq 1

should read

expect(transfer_class.scan(/@sender.valid\? \&\& @receiver.valid\?/).length).to eq 1

**Comment by vicfriedman** [comment]
Hey @AdamKing0126,

Thanks so much for opening an issue! I went ahead and fixed the tests to make them actually test the both_valid method, however, I do think you have a bug in your code.

On line 20 of `lib/bank_account.rb`, you're missing an `@` before `balance`. I do think you have other bugs going on, so I would take another look!

Thanks again!
