### ISSUE TITLE
Issue with test "rejects a transfer if the sender doesn't have a valid account"

### ISSUE THREAD

**Issue by adamjgordon28** [learn-co-curriculum/oo-banking#2]
Notice that this request doesn't make any reference to the balance of the account before transfer, but rather just the validity of the account. If this was intentional and coders are supposed to use their common sense with this, then please disregard. Just wanted to bring to your attention unless you meant to put a line in specifying that bank account balance should be >= transfer amount

**Comment by maxwellbenton** [comment]
Hi @adamjgordon28,

Thank you for providing this feedback. We agreed and have updated this lab's test to be a bit more specific. The test on rejecting transfers now mentions funds in the account and runs an additional check to test if rejection with occur if an account is closed, making it more accurate to the goal of writing code to see if the transfer accounts are valid or not.

Thank you for this contribution!
