### ISSUE TITLE
There are extra #describe blocks for BankAccount and Transfer in the tests.

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/oo-banking#23]
In the rspec tests for the BankAccount and Transfer classes, there are extra #describe blocks for BankAccount and Transfer, which leads to test output such as:

1) Transfer Transfer #reverse_transfer can reverse a transfer between two accounts

This isn't a huge issue, but it does affect the readability of the tests. I have attached screenshots for further clarity. Note that the second #describe block for BankAccount only surrounds the tests for #initialize, whereas the second #describe block for Transfer surrounds all of the tests.

Thanks for checking this out!

Sdcrouse

BankAccount tests and output:

![oo bank account screenshot](https://user-images.githubusercontent.com/38870640/45251209-1f80c880-b2f7-11e8-8796-a6bf7a4b09cf.gif)

Transfer tests and output:

![oo bank account screenshot 2](https://user-images.githubusercontent.com/38870640/45251212-2f98a800-b2f7-11e8-8212-df0a4928c9c2.gif)

**Comment by jenmyers** [comment]
Resolved in #24
